restore workflow call

diff --git a/.github/workflows/call_review.yml b/.github/workflows/call_review.yml
--- a/.github/workflows/call_review.yml
+++ b/.github/workflows/call_review.yml
@@ -21,8 +21,6 @@ jobs:
     steps:
       - uses: actions/checkout@v4
         name: Checkout
-        # with:
-        #   ref: ${{ github.ref_name }}
 
       # this workaround is necessary to pass the environment value to the next job
       # unexpectly, global env vars cannot be read to set the environment and I don't
@@ -52,47 +50,44 @@ jobs:
           tenant-id: ${{ secrets.AZURE_TENANT_ID }}
           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
 
-      - name: Terraform Plan
-        id: plan
-        run: |
-          export PATH="${HOME}/bin:$PATH"
-          export ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID_CI }}
-          export ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}
-          export ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}
-          export ARM_USE_OIDC=true
-          export ARM_USE_AZUREAD=true
-          export ARM_STORAGE_USE_AZUREAD=true
+      # - name: Terraform Plan
+      #   id: plan
+      #   run: |
+      #     export PATH="${HOME}/bin:$PATH"
+      #     export ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID_CI }}
+      #     export ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}
+      #     export ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}
+      #     export ARM_USE_OIDC=true
+      #     export ARM_USE_AZUREAD=true
+      #     export ARM_STORAGE_USE_AZUREAD=true
 
-          cd ${{ inputs.dir }}
+      #     cd ${{ inputs.dir }}
 
-          bash terraform.sh plan ${{ steps.setenv.outputs.environment }} -lock-timeout=3000s -out=tfplan-${{ steps.setenv.outputs.environment }}-${{ github.sha }} -input=fals
-        continue-on-error: true
+      #     bash terraform.sh plan ${{ steps.setenv.outputs.environment }} -lock-timeout=3000s -out=tfplan-${{ steps.setenv.outputs.environment }}-${{ github.sha }} -input=fals
+      #   continue-on-error: true
 
       - uses: actions/github-script@v6
-        # if: github.event_name == 'pull_request'
-        env:
-          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
         with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
+          # github-token: ${{ secrets.GITHUB_TOKEN }}
           script: |
             const { data: comments } = await github.rest.issues.listComments({
               owner: context.repo.owner,
               repo: context.repo.repo,
               issue_number: context.issue.number
             })
+
             const botComment = comments.find(comment => {
               return comment.user.type === 'Bot' && comment.body.includes('Terraform Plan')
             })
 
-            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+            const output = `#### Terraform Plan 📖
 
             <details><summary>Show Plan</summary>
 
             \`\`\`\n
-            ${process.env.PLAN}
             \`\`\`
 
-            </details>
+            </details>`;
 
             if (botComment) {
               github.rest.issues.updateComment({
@@ -110,9 +105,9 @@ jobs:
               })
             }
 
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+      # - name: Terraform Plan Status
+      #   if: steps.plan.outcome == 'failure'
+      #   run: exit 1
 
       # - name: Terraform Plan
       #   uses: pagopa/terraform-preapply-azure-action@54ded8cda3437c3f6a9f46baf69cb321ce82f5cd
