fix: Fixed pipeline for publish contracts (#929)
Fixed pipeline

diff --git a/.github/workflows/call_publish_contracts_template.yml b/.github/workflows/call_publish_contracts_template.yml
--- a/.github/workflows/call_publish_contracts_template.yml
+++ b/.github/workflows/call_publish_contracts_template.yml
@@ -14,13 +14,12 @@ on:
 env:
   STORAGE_ACCOUNT_NAME: "sc${{ inputs.environment_short }}weuardocumentsst01"
   STORAGE_CONTAINER: "sc-${{ inputs.environment_short }}-documents-blob"
-  STORAGE_ACCOUNT_RG: "selc-${{ inputs.environment_short }}-documents-storage-rg"  
+  STORAGE_ACCOUNT_RG: "selc-${{ inputs.environment_short }}-documents-storage-rg"
   ARM_USE_OIDC: true
   ARM_USE_AZUREAD: true
   ARM_STORAGE_USE_AZUREAD: true
 
 jobs:
-  
   publish:
     name: Publish contracts template ${{ inputs.environment }}
     runs-on: ubuntu-24.04
@@ -31,44 +30,42 @@ jobs:
       contents: read
 
     steps:
+      - name: Checkout
+        id: checkout
+        uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707
+        with:
+          persist-credentials: false
+          fetch-depth: 0
 
-    - name: Checkout
-      id: checkout
-      uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707
-      with:
-        persist-credentials: false
-        fetch-depth: 0
+      - name: Azure Login
+        id: az_login
+        uses: azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2
+        with:
+          client-id: ${{ secrets.ARM_CLIENT_ID }}
+          tenant-id: ${{ vars.ARM_TENANT_ID }}
+          subscription-id: ${{ vars.ARM_SUBSCRIPTION_ID }}
 
-    - name: Azure Login
-      id: az_login
-      uses: azure/login@a65d910e8af852a8061c627c456678983e180302
-      with:
-        client-id: ${{ secrets.ARM_CLIENT_ID }}
-        tenant-id: ${{ vars.ARM_TENANT_ID }}
-        subscription-id: ${{ vars.ARM_SUBSCRIPTION_ID }}
+      - name: Upload to blob storage
+        id: storage_upload
+        uses: azure/CLI@b0e31ae20280d899279f14c36e877b4c6916e2d3
+        with:
+          inlineScript: |
+            upload_status=$(az storage blob upload-batch \
+            --connection-string "${{ secrets.STORAGE_CONNECTION_STRING_DOCUMENTS }}" \
+            --source './src/core/contracts_template/contracts/' \
+            --destination "${{ env.STORAGE_CONTAINER }}/contracts" \
+            --overwrite)
 
-    # - name: Install azcopy
-    #   run: |
-    #     wget -O azcopy_v10.tar.gz https://aka.ms/downloadazcopy-v10-linux && tar -xf azcopy_v10.tar.gz --strip-components=1
-    
-    - name: Upload to blob storage
-      run: |
-        upload_status=$(az storage blob upload-batch \
-        --connection-string "${{ secrets.STORAGE_CONNECTION_STRING_DOCUMENTS }}" \
-        --source './src/core/contracts_template/contracts/' \
-        --destination "${{ env.STORAGE_CONTAINER }}/contracts" \
-        --overwrite)
+            echo "${upload_status}"
+            if [[ $? -eq 0 ]]; then
+              echo "Upload success."
+            else
+              echo "Error during contracts upload batch."
+              exit 1  # Esce dallo step con codice di errore
+            fi
 
-        echo "${upload_status}"
-        if [[ $? -eq 0 ]]; then
-          echo "Upload success."
-        else
-          echo "Error during contracts upload batch."
-          exit 1  # Esce dallo step con codice di errore
-        fi
-
-    - name: Azure Logout
-      id: az_logout
-      if: always()
-      run: |
-        az logout        
+      - name: Azure Logout
+        id: az_logout
+        if: always()
+        run: |
+          az logout
